version: '3'
services:
  kafdrop:
    image: obsidiandynamics/kafdrop:latest
    ports:
      - 9000:9000
    environment:
      - "KAFKA_BROKERCONNECT=${MSK_BOOTSTRAP_BROKERS}"
      - "JVM_OPTS=-Xms32M -Xmx64M"
      - "SERVER_SERVLET_CONTEXTPATH=/"
