{
 "title": "Carbon-relay-ng",
 "tags": [ "telemetry" ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_GRAPHITE", "label": "datasource", "query": "graphite" },
   {
    "name": "instance",
    "query": "service_is_carbon-relay-ng.instance_is_*"
   },
   {
    "name": "dest",
    "query": "service_is_carbon-relay-ng.instance_is_$instance.mtype_is_counter.dest_is_*"
   }
  ]
 },
 "panels": [
  {
   "title": "$instance incoming",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(perSecond(service_is_carbon-relay-ng.instance_is_$instance.mtype_is_counter.unit_is_Metric.*), 4)"
    },
    {
     "target": "alias(perSecond(service_is_carbon-relay-ng.instance_is_$instance.mtype_is_counter.unit_is_Err.type_is_invalid), 'invalid')"
    },
    {
     "target": "alias(perSecond(service_is_carbon-relay-ng.instance_is_$instance.mtype_is_counter.unit_is_Err.type_is_out_of_order), 'out-of-order')"
    }
   ]
  },
  {
   "title": "dest metric directions",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(perSecond(service_is_carbon-relay-ng.instance_is_$instance.mtype_is_counter.dest_is_$dest.unit_is_Metric.direction_is_out), 'to tcp')"
    },
    {
     "target": "alias(perSecond(service_is_carbon-relay-ng.instance_is_$instance.mtype_is_counter.spool_is_$dest.unit_is_Metric.status_is_incomingRT), 'to spool')"
    }
   ]
  },
  {
   "title": "dest metric drops",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(derivative(service_is_carbon-relay-ng.instance_is_$instance.mtype_is_counter.dest_is_$dest.unit_is_Metric.action_is_drop.*),6)"
    }
   ]
  },
  {
   "title": "dest Errors",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(perSecond(service_is_carbon-relay-ng.instance_is_$instance.mtype_is_counter.dest_is_$dest.unit_is_Err.*), 5)"
    }
   ]
  },
  {
   "title": "memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "bytes", "label": "allocation" }
   ],
   "targets": [
    {
     "target": "alias(sumSeries(perSecond(carbon-relay-ng.stats.$instance.memory.total_bytes_allocated.counter64)), 'alloc rate')"
    },
    {
     "target": "alias(sumSeries(carbon-relay-ng.stats.$instance.memory.bytes.allocated_in_heap.gauge64), 'allocated in heap')"
    },
    {
     "target": "alias(sumSeries(carbon-relay-ng.stats.$instance.process.resident_memory_bytes.gauge64), 'rss')"
    },
    {
     "target": "aliasByNode(sumSeries(perSecond(carbon-relay-ng.stats.$instance.process.minor_page_faults.counter64)), 5)"
    },
    {
     "target": "aliasByNode(sumSeries(perSecond(carbon-relay-ng.stats.$instance.process.major_page_faults.counter64)), 5)"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 8 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "target": "alias(averageSeries(carbon-relay-ng.stats.$instance.memory.gc.cpu_fraction.gauge32), 'GC cpu fraction - promille')"
    },
    {
     "target": "alias(sumSeries(perSecond(carbon-relay-ng.stats.$instance.process.cpu_seconds_total.counter64)), 'CPU usage')"
    }
   ]
  },
  {
   "title": "Golang GC",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 8 },
   "yaxes": [
    { "format": "hertz" }
   ],
   "targets": [
    {
     "target": "alias(averageSeries(perSecond(carbon-relay-ng.stats.$instance.memory.total_gc_cycles.counter64)), 'collections')"
    },
    {
     "target": "alias(averageSeries(carbon-relay-ng.stats.$instance.memory.gc.last_duration.gauge64), 'duration')"
    }
   ]
  },
  {
   "title": "conn Flush size",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "target": "alias(service_is_carbon-relay-ng.instance_is_$instance.mtype_is_gauge.dest_is_$dest.unit_is_B.what_is_FlushSize.type_is_ticker.stat_is_max, 'ticker max')"
    },
    {
     "target": "alias(service_is_carbon-relay-ng.instance_is_$instance.mtype_is_gauge.dest_is_$dest.unit_is_B.what_is_FlushSize.type_is_ticker.stat_is_max_99, 'ticker 99')"
    },
    {
     "target": "alias(service_is_carbon-relay-ng.instance_is_$instance.mtype_is_gauge.dest_is_$dest.unit_is_B.what_is_FlushSize.type_is_ticker.stat_is_mean,'ticker mean')"
    },
    {
     "target": "alias(service_is_carbon-relay-ng.instance_is_$instance.mtype_is_gauge.dest_is_$dest.unit_is_B.what_is_FlushSize.type_is_manual.stat_is_max, 'manual max')"
    },
    {
     "target": "alias(service_is_carbon-relay-ng.instance_is_$instance.mtype_is_gauge.dest_is_$dest.unit_is_B.what_is_FlushSize.type_is_manual.stat_is_max_99, 'manual 99')"
    },
    {
     "target": "alias(service_is_carbon-relay-ng.instance_is_$instance.mtype_is_gauge.dest_is_$dest.unit_is_B.what_is_FlushSize.type_is_manual.stat_is_mean, 'manual mean')"
    },
    {
     "target": "alias(service_is_carbon-relay-ng.instance_is_$instance.mtype_is_gauge.dest_is_$dest.unit_is_B.what_is_FlushSize.type_is_overflow.stat_is_max,'overflow max')"
    },
    {
     "target": "alias(service_is_carbon-relay-ng.instance_is_$instance.mtype_is_gauge.dest_is_$dest.unit_is_B.what_is_FlushSize.type_is_overflow.stat_is_max99, 'overflow 99')"
    },
    {
     "target": "alias(service_is_carbon-relay-ng.instance_is_$instance.mtype_is_gauge.dest_is_$dest.unit_is_B.what_is_FlushSize.type_is_overflow.mean,\"overflow mean\")"
    }
   ]
  },
  {
   "title": "conn metrics in buffer",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(service_is_carbon-relay-ng.instance_is_$instance.mtype_is_gauge.dest_is_$dest.unit_is_Metric.what_is_numBuffered, 'numBuffered')"
    },
    {
     "target": "alias(service_is_carbon-relay-ng.instance_is_$instance.mtype_is_gauge.dest_is_$dest.unit_is_Metric.what_is_bufferSize, 'bufferSize')"
    },
    {
     "target": "alias(service_is_carbon-relay-ng.instance_is_$instance.mtype_is_gauge.what_is_virtual_memory.unit_is_Byte, 'memory-usage')"
    },
    {
     "target": "alias(service_is_carbon-relay-ng.instance_is_$instance.mtype_is_gauge.what_is_memory_allocated.unit_is_Byte, 'allocated memory')"
    }
   ]
  },
  {
   "title": "conn flush durations",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 15 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "target": "alias(service_is_carbon-relay-ng.instance_is_$instance.mtype_is_gauge.unit_is_ns.dest_is_$dest.what_is_durationFlush.type_is_ticker.stat_is_max, '\"ticker max\"')"
    },
    {
     "target": "alias(service_is_carbon-relay-ng.instance_is_$instance.mtype_is_gauge.unit_is_ns.dest_is_$dest.what_is_durationFlush.type_is_ticker.stat_is_mean, '\"ticker mean\"')"
    },
    {
     "target": "alias(service_is_carbon-relay-ng.instance_is_$instance.mtype_is_gauge.unit_is_ns.dest_is_$dest.what_is_durationFlush.type_is_overflow.stat_is_max, '\"overflow max\"')"
    },
    {
     "target": "alias(service_is_carbon-relay-ng.instance_is_$instance.mtype_is_gauge.unit_is_ns.dest_is_$dest.what_is_durationFlush.type_is_overflow.stat_is_mean, '\"overflow mean\"')"
    }
   ]
  },
  {
   "title": "spool inputs",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(service_is_carbon-relay-ng.instance_is_$instance.mtype_is_counter.spool_is_$dest.unit_is_Metric.*, 5)"
    },
    {}
   ]
  },
  {
   "title": "spool metrics in buffer",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 22 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "target": "alias(service_is_carbon-relay-ng.instance_is_$instance.mtype_is_gauge.spool_is_$dest.unit_is_Metric.status_is_buffered, 'buffered')"
    }
   ]
  },
  {
   "title": "spool durations",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 22 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "target": "aliasByNode(service_is_carbon-relay-ng.instance_is_$instance.mtype_is_gauge.unit_is_ns.spool_is_$dest.operation_is*.stat_is_max_50, 5, 6)"
    },
    {
     "target": "aliasByNode(service_is_carbon-relay-ng.instance_is_$instance.mtype_is_gauge.unit_is_ns.spool_is_$dest.operation_is*.stat_is_max_95, 5, 6)"
    },
    {
     "target": "aliasByNode(service_is_carbon-relay-ng.instance_is_$instance.mtype_is_gauge.unit_is_ns.spool_is_$dest.operation_is*.stat_is_max, 5, 6)"
    },
    {
     "target": "aliasByNode(service_is_carbon-relay-ng.instance_is_$instance.mtype_is_gauge.unit_is_ns.spool_is_$dest.operation_is*.stat_is_mean, 5, 6)"
    }
   ]
  },
  {
   "title": "Aggregator input",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "refCount": 1,
     "target": "alias(sumSeries(perSecond(service_is_carbon-relay-ng.instance_is_$instance.mtype_is_counter.module_is_aggregator.unit_is_Metric.what_is_TooOld)), 'too old')"
    },
    {
     "refCount": 1,
     "target": "alias(diffSeries(keepLastValue(service_is_carbon-relay-ng.instance_is_$instance.mtype_is_gauge.module_is_aggregator.unit_is_s.what_is_timestamp_received.type_is_min,2), #B),'min')",
     "targetFull": "alias(diffSeries(keepLastValue(service_is_carbon-relay-ng.instance_is_$instance.mtype_is_gauge.module_is_aggregator.unit_is_s.what_is_timestamp_received.type_is_min,2), time(\"now\",step=1)),'min')"
    },
    {
     "target": "alias(diffSeries(keepLastValue(service_is_carbon-relay-ng.instance_is_$instance.mtype_is_gauge.module_is_aggregator.unit_is_s.what_is_timestamp_received.type_is_max,2),#B),'max')",
     "targetFull": "alias(diffSeries(keepLastValue(service_is_carbon-relay-ng.instance_is_$instance.mtype_is_gauge.module_is_aggregator.unit_is_s.what_is_timestamp_received.type_is_max,2),time(\"now\",step=1)),'max')"
    }
   ]
  },
  {
   "title": "aggregators inbound",
   "type": "graph",
   "gridPos": { "h": 5, "w": 16, "x": 8, "y": 26 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "target": "aliasSub(perSecond(service_is_carbon-relay-ng.instance_is_$instance.mtype_is_counter.unit_is_Metric.direction_is_in.aggregator_is_*), '.*instance_is_([^\\.]+).*aggregator_is_([^\\.]+)', 'metrics going into aggregator \\1.\\2')"
    }
   ]
  },
  {
   "title": "aggregators outbound and flushing",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "target": "alias(service_is_carbon-relay-ng.instance_is_$instance.*.unit_is_aggregator.what_is_flush_waiting, 'aggregators waiting to flush')"
    },
    {
     "target": "aliasSub(perSecond(service_is_carbon-relay-ng.instance_is_$instance.mtype_is_counter.unit_is_Metric.direction_is_out.aggregator_is_*), '.*instance_is_([^\\.]+).*aggregator_is_([^\\.]+)', 'metrics going out of aggregator \\1.\\2')"
    }
   ]
  }
 ]
}