version: '3.4'
services:
  haproxy-logs:
    image: telemetry-log-proxy:latest
    environment:
      - "KAFKA_BROKER_1=127.0.0.1:39092"
      - "KAFKA_BROKER_2=${KAFKA_BROKER_2}"
      - "KAFKA_BROKER_3=${KAFKA_BROKER_3}"
      - "KAFKA_TOPIC=${KAFKA_LOGS_TOPIC}"
    ports:
      - "127.0.0.1:4444:4444"
    network_mode: host
  logstash-producer:
    image: fluent/fluent-bit:latest
    command: "/fluent-bit/bin/fluent-bit -i cpu -o kafka -p brokers=127.0.0.1:4444 -p topics=test2"
    depends_on:
      - "haproxy-logs"
    environment:
      - "LOG_LEVEL=error"
      - "KAFKA_BOOTSTRAP_BROKERS=localhost:4444"
      - "KAFKA_TOPIC=${KAFKA_TOPIC}"
    network_mode: host
