version: '2.2'

services:
  create_certs:
    image: docker.elastic.co/elasticsearch/elasticsearch:${VERSION}
    container_name: create_certs
    command: >
      bash -c '
        yum install -y -q -e 0 unzip;
        KEY_PASSPHRASE=$$(cat ./passphrase)
        bin/elasticsearch-certutil ca --silent \
                                      --pass $${KEY_PASSPHRASE} \
                                      --out elastic-stack-ca.p12;
        bin/elasticsearch-certutil cert --silent \
                                        --pass $${KEY_PASSPHRASE} \
                                        --out elastic-certificates.zip \
                                        --ca elastic-stack-ca.p12 \
                                        --ca-pass $${KEY_PASSPHRASE} \
                                        --in instances.yml;
        unzip -o elastic-certificates.zip -d /certs;
        chown -R 1000:0 /certs
      '
    working_dir: /usr/share/elasticsearch
    volumes:
      - certs:/certs
      - ./config-certs/instances.yml:/usr/share/elasticsearch/instances.yml
      - ./passphrase:/usr/share/elasticsearch/passphrase:ro
    networks:
      - elastic

volumes:
  certs:
    driver: local

networks:
  elastic:
    driver: bridge
