version: '2.2'

services:
  create_keystore:
    image: docker.elastic.co/elasticsearch/elasticsearch:${VERSION}
    container_name: create_keystore
    command: >
      bash -c "
        yum install -y -q -e 0 openssl;
        bin/elasticsearch-keystore create
        # KEY_PASSPHRASE=$$(openssl rand -base64 32)
        KEY_PASSPHRASE=${KEY_PASSPHRASE}
        echo $${KEY_PASSPHRASE} > ./config/passphrase
        for KEY in xpack.security.http.ssl.secure_key_passphrase \
                   xpack.security.http.ssl.keystore.secure_password \
                   xpack.security.http.ssl.keystore.secure_key_password \
                   xpack.security.http.ssl.truststore.secure_password \
                   xpack.security.transport.ssl.secure_key_passphrase \
                   xpack.security.transport.ssl.keystore.secure_password \
                   xpack.security.transport.ssl.keystore.secure_key_password \
                   xpack.security.transport.ssl.truststore.secure_password; do
        	echo $${KEY_PASSPHRASE} | bin/elasticsearch-keystore add $${KEY}
        done
        bin/elasticsearch-keystore list
      "
    working_dir: /usr/share/elasticsearch
    volumes:
      - ./config:/usr/share/elasticsearch/config
    networks:
      - elastic

networks:
  elastic:
    driver: bridge
