version: '2.2'

services:
  create_certs:
    image: docker.elastic.co/elasticsearch/elasticsearch:${VERSION}
    container_name: create_certs
    command: >
      bash -c '
        yum install -y -q -e 0 unzip openssl;
        KEY_PASSPHRASE=$$(cat ./passphrase);
        mkdir -p /certs/ca
        bin/elasticsearch-certutil ca --silent \
                                      --pass telemetry \
                                      --out elastic-stack-ca.p12;
        bin/elasticsearch-certutil cert --silent \
                                        --pass "" \
                                        --out es-certs.zip \
                                        --ca elastic-stack-ca.p12 \
                                        --ca-pass telemetry \
                                        --in es.yml;
        bin/elasticsearch-certutil cert --silent \
                                        --out kibana-certs.zip \
                                        --ca elastic-stack-ca.p12 \
                                        --ca-pass telemetry \
                                        --pem \
                                        --in kibana.yml;
        unzip -oq es-certs.zip -d /certs;
        unzip -oq kibana-certs.zip -d /certs;
        openssl pkcs12 -in elastic-stack-ca.p12 -passin pass:telemetry \
                       -out /certs/ca/ca.pem -passout pass: -nokeys;
        chown -R 1000:0 /certs && ls -laR /certs;
      '
    working_dir: /usr/share/elasticsearch
    volumes:
      - certs:/certs
      - ./config-certs/es.yml:/usr/share/elasticsearch/es.yml
      - ./config-certs/kibana.yml:/usr/share/elasticsearch/kibana.yml
      - ./passphrase:/usr/share/elasticsearch/passphrase:ro
    networks:
      - elastic

volumes:
  certs:
    driver: local

networks:
  elastic:
    driver: bridge
