version: '2.2'

services:
  es01.telemetry.internal:
    image: docker.elastic.co/elasticsearch/elasticsearch:${VERSION}
    container_name: es01
    environment:
      - node.name=es01.telemetry.internal
      - discovery.seed_hosts=es02.telemetry.internal,es03.telemetry.internal
      - cluster.initial_master_nodes=es01.telemetry.internal,es02.telemetry.internal,es03.telemetry.internal
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
#      - xpack.security.http.ssl.enabled=true
#      - xpack.security.http.ssl.key=$CERTS_DIR/es01/es01.key
#      - xpack.security.http.ssl.certificate_authorities=$CERTS_DIR/ca/ca.crt
#      - xpack.security.http.ssl.certificate=$CERTS_DIR/es01/es01.crt
#      - xpack.security.transport.ssl.enabled=true
#      - xpack.security.transport.ssl.verification_mode=certificate
#      - xpack.security.transport.ssl.certificate_authorities=$CERTS_DIR/ca/ca.crt
#      - xpack.security.transport.ssl.certificate=$CERTS_DIR/es01/es01.crt
#      - xpack.security.transport.ssl.key=$CERTS_DIR/es01/es01.key
      - xpack.security.http.ssl.enabled=true
      - xpack.security.http.ssl.keystore.path=$CERTS_DIR/es01/es01.p12
#      - xpack.security.http.ssl.keystore.password=telemetry
#      - xpack.security.http.ssl.keystore.key_password=telemetry
      - xpack.security.http.ssl.truststore.path=$CERTS_DIR/es01/es01.p12
      - xpack.security.http.ssl.client_authentication=optional
      - xpack.security.transport.ssl.enabled=true
      - xpack.security.transport.ssl.verification_mode=certificate
      - xpack.security.transport.ssl.keystore.path=$CERTS_DIR/es01/es01.p12
#      - xpack.security.transport.ssl.keystore.password=telemetry
#      - xpack.security.transport.ssl.keystore.key_password=telemetry
      - xpack.security.transport.ssl.truststore.path=$CERTS_DIR/es01/es01.p12
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data01:/usr/share/elasticsearch/data
      - certs:$CERTS_DIR
      - ./config-es/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./config-es/log4j2.properties:/usr/share/elasticsearch/config/log4j2.properties
#      - ./logs/01:/usr/share/elasticsearch/logs:rw
    ports:
      - 9200:9200
    networks:
      - elastic
    healthcheck:
      test: curl --cacert $CERTS_DIR/ca.crt -s https://es01.telemetry.internal:9200 >/dev/null; if [[ $$? == 52 ]]; then echo 0; else echo 1; fi
      interval: 30s
      timeout: 10s
      retries: 5

  es02.telemetry.internal:
    image: docker.elastic.co/elasticsearch/elasticsearch:${VERSION}
    container_name: es02
    environment:
      - node.name=es02.telemetry.internal
      - discovery.seed_hosts=es01.telemetry.internal,es03.telemetry.internal
      - cluster.initial_master_nodes=es01.telemetry.internal,es02.telemetry.internal,es03.telemetry.internal
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
#      - xpack.security.http.ssl.enabled=true
#      - xpack.security.http.ssl.key=$CERTS_DIR/es02/es02.key
#      - xpack.security.http.ssl.certificate_authorities=$CERTS_DIR/ca/ca.crt
#      - xpack.security.http.ssl.certificate=$CERTS_DIR/es02/es02.crt
#      - xpack.security.transport.ssl.enabled=true
#      - xpack.security.transport.ssl.verification_mode=certificate
#      - xpack.security.transport.ssl.certificate_authorities=$CERTS_DIR/ca/ca.crt
#      - xpack.security.transport.ssl.certificate=$CERTS_DIR/es02/es02.crt
#      - xpack.security.transport.ssl.key=$CERTS_DIR/es02/es02.key
      - xpack.security.http.ssl.enabled=true
      - xpack.security.http.ssl.keystore.path=$CERTS_DIR/es02/es02.p12
#      - xpack.security.http.ssl.keystore.password=telemetry
#      - xpack.security.http.ssl.keystore.key_password=telemetry
      - xpack.security.http.ssl.truststore.path=$CERTS_DIR/es02/es02.p12
      - xpack.security.http.ssl.client_authentication=optional
      - xpack.security.transport.ssl.enabled=true
      - xpack.security.transport.ssl.verification_mode=certificate
      - xpack.security.transport.ssl.keystore.path=$CERTS_DIR/es02/es02.p12
#      - xpack.security.transport.ssl.keystore.password=telemetry
#      - xpack.security.transport.ssl.keystore.key_password=telemetry
      - xpack.security.transport.ssl.truststore.path=$CERTS_DIR/es02/es02.p12
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data02:/usr/share/elasticsearch/data
      - certs:$CERTS_DIR
      - ./config-es/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./config-es/log4j2.properties:/usr/share/elasticsearch/config/log4j2.properties
#      - ./logs/02:/usr/share/elasticsearch/logs:rw
    networks:
      - elastic

  es03.telemetry.internal:
    image: docker.elastic.co/elasticsearch/elasticsearch:${VERSION}
    container_name: es03
    environment:
      - node.name=es03.telemetry.internal
      - discovery.seed_hosts=es01.telemetry.internal,es02.telemetry.internal
      - cluster.initial_master_nodes=es01.telemetry.internal,es02.telemetry.internal,es03.telemetry.internal
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
#      - xpack.security.http.ssl.enabled=true
#      - xpack.security.http.ssl.key=$CERTS_DIR/es03/es03.key
#      - xpack.security.http.ssl.certificate_authorities=$CERTS_DIR/ca/ca.crt
#      - xpack.security.http.ssl.certificate=$CERTS_DIR/es03/es03.crt
#      - xpack.security.transport.ssl.enabled=true
#      - xpack.security.transport.ssl.verification_mode=certificate
#      - xpack.security.transport.ssl.certificate_authorities=$CERTS_DIR/ca/ca.crt
#      - xpack.security.transport.ssl.certificate=$CERTS_DIR/es03/es03.crt
#      - xpack.security.transport.ssl.key=$CERTS_DIR/es03/es03.key
      - xpack.security.http.ssl.enabled=true
      - xpack.security.http.ssl.keystore.path=$CERTS_DIR/es03/es03.p12
#      - xpack.security.http.ssl.keystore.password=telemetry
#      - xpack.security.http.ssl.keystore.key_password=telemetry
      - xpack.security.http.ssl.truststore.path=$CERTS_DIR/es03/es03.p12
      - xpack.security.http.ssl.client_authentication=optional
      - xpack.security.transport.ssl.enabled=true
      - xpack.security.transport.ssl.verification_mode=certificate
      - xpack.security.transport.ssl.keystore.path=$CERTS_DIR/es03/es03.p12
#      - xpack.security.transport.ssl.keystore.password=telemetry
#      - xpack.security.transport.ssl.keystore.key_password=telemetry
      - xpack.security.transport.ssl.truststore.path=$CERTS_DIR/es03/es03.p12
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data03:/usr/share/elasticsearch/data
      - certs:$CERTS_DIR
      - ./config-es/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./config-es/log4j2.properties:/usr/share/elasticsearch/config/log4j2.properties
#      - ./logs/03:/usr/share/elasticsearch/logs:rw
    networks:
      - elastic

  kib01.telemetry.internal:
    image: docker.elastic.co/kibana/kibana:${VERSION}
    container_name: kib01
    depends_on: {"es01.telemetry.internal": {"condition": "service_healthy"}}
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_PASSWORD: 7DDLO1nO9M4F0ykKQ6DL
    volumes:
      - certs:/usr/share/kibana/config/certificates
      - ./config-kibana/kibana.yml:/usr/share/kibana/config/kibana.yml
    networks:
      - elastic

volumes:
  certs:
    driver: local
  data01:
    driver: local
  data02:
    driver: local
  data03:
    driver: local
  keystore:
    driver: local

networks:
  elastic:
    driver: bridge
