version: '2.2'

services:
  es01.telemetry.internal:
    image: docker.elastic.co/elasticsearch/elasticsearch:${VERSION}
    container_name: es01
    command: /usr/share/elasticsearch/config-tmp/entrypoint.sh
    environment:
      - KEY_PASSPHRASE=${KEY_PASSPHRASE}
      - node.name=es01.telemetry.internal
      - ${ES_JAVA_OPTS:-/dev/null}
      - ${SEED_HOSTS_ES01:-/dev/null}
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data01:/usr/share/elasticsearch/data
      - certs:$CERTS_DIR
      - config:/usr/share/elasticsearch/config-tmp
      - ./logs/01:/usr/share/elasticsearch/logs:rw
    ports:
      - 9200:9200
    networks:
      - elastic
    healthcheck:
      test: curl --cacert $CERTS_DIR/ca.telemetry.internal.crt -s https://es01.telemetry.internal:9200 >/dev/null; if [[ $$? == 52 ]]; then echo 0; else echo 1; fi
      interval: 30s
      timeout: 10s
      retries: 5

  es02.telemetry.internal:
    image: docker.elastic.co/elasticsearch/elasticsearch:${VERSION}
    container_name: es02
    command: /usr/share/elasticsearch/config-tmp/entrypoint.sh
    environment:
      - KEY_PASSPHRASE=${KEY_PASSPHRASE}
      - node.name=es02.telemetry.internal
      - ${ES_JAVA_OPTS:-/dev/null}
      - ${SEED_HOSTS_ES02:-/dev/null}
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data02:/usr/share/elasticsearch/data
      - certs:$CERTS_DIR
      - config:/usr/share/elasticsearch/config-tmp
      - ./logs/02:/usr/share/elasticsearch/logs:rw
    networks:
      - elastic

  es03.telemetry.internal:
    image: docker.elastic.co/elasticsearch/elasticsearch:${VERSION}
    container_name: es03
    command: /usr/share/elasticsearch/config-tmp/entrypoint.sh
    environment:
      - KEY_PASSPHRASE=${KEY_PASSPHRASE}
      - node.name=es03.telemetry.internal
      - ${ES_JAVA_OPTS:-/dev/null}
      - ${SEED_HOSTS_ES03:-/dev/null}
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data03:/usr/share/elasticsearch/data
      - certs:$CERTS_DIR
      - config:/usr/share/elasticsearch/config-tmp
      - ./logs/03:/usr/share/elasticsearch/logs:rw
    networks:
      - elastic

  kib01.telemetry.internal:
    image: docker.elastic.co/kibana/kibana:${VERSION}
    container_name: kib01
    depends_on: {"es01.telemetry.internal": {"condition": "service_healthy"}}
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_PASSWORD: 89VeduPWCd9D9m6i5ZAI
      SERVER_SSL_KEYPASSPHRASE: ${KEY_PASSPHRASE}
    volumes:
      - certs:/usr/share/kibana/config/certificates
      - ./config-kibana/kibana.yml:/usr/share/kibana/config/kibana.yml
    networks:
      - elastic

volumes:
  certs:
    driver: local
  config:
    driver: local
  data01:
    driver: local
  data02:
    driver: local
  data03:
    driver: local

networks:
  elastic:
    driver: bridge
