version: '2.2'

services:
  import_certs:
    image: docker.elastic.co/elasticsearch/elasticsearch:${VERSION}
    container_name: import_certs
    command: >
      bash -c '
        yum install -y -q -e 0 unzip openssl;
        KEY_PASSPHRASE=$$(cat ./passphrase);
        cp ./ca.crt ./keystore.p12 ./truststore.p12 /certs
        openssl pkcs12 -in /certs/keystore.p12 -out out_key -nodes -passin pass:$${KEY_PASSPHRASE}
        openssl x509 -text -in out_key | grep telemetry.internal
        openssl pkcs12 -in /certs/truststore.p12 -out out_trust -nodes -passin pass:$${KEY_PASSPHRASE}
        openssl x509 -text -in out_trust | grep Subject:
        rm -f /certs/out_*
        chown -R 1000:0 /certs && ls -laR /certs;
      '
    working_dir: /usr/share/elasticsearch
    volumes:
      - certs:/certs
      - ./certs/ca.crt:/usr/share/elasticsearch/ca.crt
      - ./certs/keystore.p12:/usr/share/elasticsearch/keystore.p12
      - ./certs/truststore.p12:/usr/share/elasticsearch/truststore.p12
      - ./passphrase:/usr/share/elasticsearch/passphrase:ro
    networks:
      - elastic

volumes:
  certs:
    driver: local

networks:
  elastic:
    driver: bridge
