version: '3'
services:
  logstash-consumer:
    image: '$IMAGE_TAG'
    environment:
      - "LOG_LEVEL=error"
      - "KAFKA_BOOTSTRAP_BROKERS=${MSK_BOOTSTRAP_BROKERS}"
      - "ES_HOST=${ES_HOST}"
      - "KAFKA_TOPIC=${KAFKA_TOPIC}"
      - "ES_PORT=${ES_PORT}"
    logging:
      driver: "awslogs"
      options:
        awslogs-region: "eu-west-2"
        awslogs-group: "/aws/ecs/internal-staging/telemetry/logstash-consumer"
        awslogs-stream-prefix: "playground"
