FROM evenlights/collectd
RUN python --version
RUN pip --version
# RUN pip download --no-cache-dir --verbose "foo<0" 2>&1 | grep Looking
# RUN pip download --no-cache-dir --verbose "foo<0" 2>&1 | grep 'location(s) to search' -A5
# RUN pip download json-flatten -vvv
# RUN pip install json-flatten