version: '3'
services:
  ksql-server:
    image: confluentinc/cp-ksql-server:5.3.1
    ports:
      - "8088:8088"
    environment:
      - "KSQL_BOOTSTRAP_SERVERS=${MSK_BOOTSTRAP_BROKERS}"
      - "KSQL_LISTENERS=http://0.0.0.0:8088/"
      - "KSQL_KSQL_SERVICE_ID=ksql-server_"
