FROM fluent/fluentd:v1.4-1
MAINTAINER Telemetry <service_telemetry.dog+bristol@digital.hmrc.gov.uk>

USER root

RUN apk add --no-cache --update --virtual .build-deps sudo build-base ruby-dev \
 && sudo gem install fluent-plugin-riemann \
 && sudo gem sources --clear-all \
 && apk del .build-deps \
 && rm -rf /home/fluent/.gem/ruby/2.5.0/cache/*.gem

COPY riemann-fluentd-fluent.conf /fluentd/etc/fluent.conf
COPY riemann-fluentd-entrypoint.sh /bin/entrypoint.sh

USER fluent
