version: '3'
services:
  kibana:
    image: docker.elastic.co/kibana/kibana:6.8.0
    ports:
      - 5601:5601
    environment:
      - ELASTICSEARCH_HOSTS=["http://${ES_HOST}:${ES_PORT}"]
    command: 
      - bash 
      - -c 
      - |
        /usr/local/bin/kibana-docker &
        echo "Waiting for Kibana to start listening ⏳"
        while [ $$(curl -s -o /dev/null -w %{http_code} http://localhost:5601/) -eq 000 ] ; do 
          sleep 5 
        done
        sleep 10
        echo "Creating index pattern"
        id=$$(curl -f -XPOST -H "Content-Type: application/json" -H "kbn-xsrf: anything" "http://localhost:5601/api/saved_objects/index-pattern" -d"{\"attributes\":{\"title\":\"logstash-*\",\"timeFieldName\":\"@timestamp\"}}" | python -c 'import sys, json; print json.load(sys.stdin)["id"]' )
        curl -XPOST -H "Content-Type: application/json" -H "kbn-xsrf: anything" "http://localhost:5601/api/kibana/settings/defaultIndex" -d"{\"value\":\"$$id\"}"
        sleep infinity

